apiVersion: v1
kind: Secret
metadata:
  name: nestjs-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres.pfbbufzewdpqrkzscjmf:4hEAbyQqbzBWphsf@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
  DIRECT_URL: "postgresql://postgres.pfbbufzewdpqrkzscjmf:4hEAbyQqbzBWphsf@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres"