resources:
  - ../../base

namespace: nestjs-prod

images:
  - name: ghcr.io/veecodekub/nestjs-cicd
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: nestjs
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nestjs-prod.veecodekub.dev