resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
  - hpa.yaml
  - network-policy.yaml

namespace: nextjs-prod

images:
  - name: ghcr.io/veecodekub/nextjs-cicd
    newTag: main-d9a9e13
    digest: sha256:50e119732a5193aeb7edd843ab368d4d87a0d347a0216ee6c2d638ebfc9c6418

patches:
  - target:
      kind: Ingress
      name: nextjs
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nextjs-prod.veecodekub.dev
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-prod
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - nextjs-prod.veecodekub.dev
            secretName: nextjs-prod-tls
  - target:
      kind: ConfigMap
      name: nextjs-config
    patch: |-
      - op: replace
        path: /data/API_URL
        value: http://nestjs.nestjs-prod.svc.cluster.local
  - target:
      kind: Deployment
      name: nextjs
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
