resources:
  - ../../base

namespace: nextjs-prod

images:
  - name: ghcr.io/veecodekub/nextjs-cicd
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: nextjs
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nextjs-prod.veecodekub.dev
  - target:
      kind: ConfigMap
      name: nextjs-config
    patch: |-
      - op: replace
        path: /data/NEXT_PUBLIC_API_URL
        value: https://nestjs-prod.veecodekub.dev
